# Generated by Django 4.2 on 2023-04-22 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=30, verbose_name='Текстовая заметка')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to='webapp.photo', verbose_name='Избранное')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_photo', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
            ],
        ),
    ]
