# Generated by Django 4.2 on 2023-04-22 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='users',
            field=models.ManyToManyField(related_name='photos', through='webapp.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
