# Generated by Django 4.2 on 2023-04-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_photo_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='note',
        ),
    ]
